<a href="https://colab.research.google.com/github/santorasu/Python-Practice/blob/master/Lab_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("The world under attack by python")
print(5+5)
print("We are not same bro")
print("Oil your own machine")
#if else statement
if 5>2:
     print("Five is greater than two")
# This is single line comment
# djjffdjf
# fdfdjfzz
a=2
print(a)
b=3.3
print(b)
c="String"
print(c)
print(a+b)
print("The type of a is ",type(a))
print("The type of b is ",type(b))
print("The type of c is ",type(c))
d=complex(34, 33)
print("type of d is ",type(d))
e=True
print("The type of d is ",type(d))
#List & Tuple
list1=[8,7,5,3,[-4,5,3,-6],["Apple","Dog","Cat"]]
print(list1)

tuple1=(("parrot","snake","Tiger"))
print(tuple1)

The world under attack by python
10
We are not same bro
Oil your own machine
Five is greater than two
2
3.3
String
5.3
The type of a is  <class 'int'>
The type of b is  <class 'float'>
The type of c is  <class 'str'>
type of d is  <class 'complex'>
The type of d is  <class 'complex'>
[8, 7, 5, 3, [-4, 5, 3, -6], ['Apple', 'Dog', 'Cat']]
('parrot', 'snake', 'Tiger')

In [ ]:
a="45"
n="2"
print(int(a)+int(n))
name=input()
print(name)
print(name[0])
print(name[1])
print(name[2])
print(name[3])
print("My name is",name)
about=input("Enter your Ocupation: ")
print("I am a",about)
x=input("Enter first number: ")
y=input("Enter Second number: ")
print(x+y)
print(int(x)+int(y))

apple= '''He said,"I want to 
eat an apple
this is another line '''
print(apple)
st= """ Hey I'm Rasu
I'm a CSE Engineer
I live in Ashulia
This is python code"""
print(st)
print("Let's use for loop\n")
for chracter in name:
    print(chracter)
for chracter in st:
    print(chracter)

47
2323
2323
2
3
2
3
My name is 2323
Enter your Ocupation: Student
I am a Student
Enter first number: 4
Enter Second number: 5
45
9
He said,"I want to
eat an apple
this is another line
 Hey I'm Rasu
I'm a CSE Engineer
I live in Ashulia
This is python code
Let's use for loop

2
3
2
3

H
e
y

I
'
m

R
a
s
u


I
'
m

a

C
S
E

E
n
g
i
n
e
e
r


I

l
i
v
e

i
n

A
s
h
u
l
i
a


T
h
i
s

i
s

p
y
t
h
o
n

c
o
d
e

In [ ]:
import time
timestamp = time.strftime('%H:%M:%S')
print(timestamp)
timestamp = time.strftime('%H')
print(timestamp)
timestamp = time.strftime('%M')
print(timestamp)
timestamp = time.strftime('%S')
print(timestamp)
# https://docs.python.org/3/library/time.html#time.strftime 

x = 4
# x is the variable to match
match x:
    # if x is 0
    case 0:
        print("x is zero")
    # case with if-condition
    case 4 if x % 2 == 0:
        print("x % 2 == 0 and case is 4")
    # Empty case with if-condition
    case _ if x < 10:
        print("x is < 10")
    # default case(will only be matched if the above cases were not matched)
    # so it is basically just an else:
    case _:
        print(x)

In [ ]:
num=0
if(num<0):
    print("Negative")
elif(num>0):
    if(num<=10):
        print("Number is between 1-10")
    elif(num>10):
        print("Number between 11-20")
    else:
        print("Number is greater then 20")   
else:
    print("Number is zero")

In [ ]:
name="Santo Rasu"
print(name[0:10])
print(name[:10])
print(name[2:10])
print(name[:])
print(name[:-4])
print(name[-9:-1])
print(len(name))

print(name.upper())
print(name.lower())
print(name.replace("Rasu","Love"))
a="!!Rasu!!!!!"
print(a.strip("!"))
print(a.rstrip("!"))

blogHeading="introduction to js"
print(blogHeading.capitalize())

str1="Welcome to Diu! Diu have big campus"
print(str1.center(40))
print(len(str1))
print(len(str1.center(40)))
print(str1.count("Diu"))
print(str1.endswith("!!!"))
print(str1.endswith("to",4,10))

str1 = "He's name is Dan. He is an honest man."
print(str1.find("Dan"))

Low="rasu"
print(Low.islower())
print(Low.isalnum())

str2 = "Welcome To Bangladesh\n"
print(str2.isalpha())
print("\nIs printable")
print(str2.isprintable())
print("\nIs Space")
print(str2.isspace())
str1="     "
print(str1.isspace())
print(str2.istitle())
str2 = "To kill a Mocking bird"
print(str2.istitle())
str1 = "Python is a Interpreted Language" 
print(str1.startswith("Python"))
str1 = "Python is a Interpreted Language" 
print(str1.swapcase())
str1 = "He's name is Dan. Dan is an honest man."
print(str1.title())

In [ ]:
i=0

for i in range(3):
    print(i)
i= 0
while(i<=3):
    print(i)
    i=i+1

#input from user in loop
while(i<40):
    i=int(input("Enter the number: "))
    print(i)
else:
    print("I'm inside else")

print("Done with loop")

#Decreasing loop
count=6
while(count>0):
    print(count)
    count=count-1
else:
    print("I'm inside else")
# infinity loop
# count= 5
# while(count>0):
#   print(count)
#   count= count + 1

#This is day 19 task
for i in range(12):
    if(i==10):
        break
    print("5 X",i+1,"=",5*(i+1))
print("Outside the loop")
#This is continue statement
for i in range(12):
    if(i==10):
        print("Skip the line")
        continue
    print("5 X",i+1,"=",5*(i+1))
    
#This is while loop statement
i = 0
while True:
    print(i)
    i=i+1
    if(i%100 == 0):
        break

In [ ]:
Name="Santo Rasu"
for i in Name:
    print(i)
    if(i=="a"):
        print("this is special")
colors = ["red", "green", "blue", "Yellow"]
for color in colors:
    print(color)
    for i in color:
        print(i)

for k in range(5):
    print(k)
print("\n")
for k in range(1,100):
    print(k)

for k in range(1,20,3):
    print(k)

In [ ]:
a=int(input("Enter your age: "))
print("Your age is: ",a)

if(a>18):
    print("You can drive")
else:
    print("You cant't drive")

print(a>18)
print(a<18)
print(a>=18)
print(a<=18)
print(a==18)
print(a!=18)

num=int(input("Enter the value of num: "))
if(num<0):
    print("Number is negative")
elif(num==0):
    print("Number is zero")
else:
    print("Number is positive")

applePrize=10
budget=200
if(budget - applePrize>50):
    print("You can buy Apple")
elif(budget - applePrize>70):
    print("Okay you can buy")
else:
    print("You cant't buy apple")

In [ ]:
def calculation(a,b):
    gmean= (a*b)/(a+b)
    print(gmean)
def isGreater(a,b):
    if(a>b):
        print("First Number is greater")
    else:
        print("Second number is greater or equal")
def isLesser(a,b):
    pass

a=9
b=8
# gmean= (a*b)/(a+b)
# print(gmean)
calculation(a,b)
isGreater(a,b)
c= 8 
d = 15
calculation(c,d)
isGreater(c,d)
# gmean2 = (c * d)/ (c*d)
# print(gmean2)

In [ ]:
def average(a,b):
    print("The average is ",(a+b)/2)

average(1,3)

def average(a=9,b=1):
    print("The average is ",(a+b)/2)

average(b=2)

def name(fname,mname="Rasu",Lname="Santo"):
    print("Hellow,",fname,mname,Lname)

name("Ami")

#Number of average
def average(*numbers):
    print(type(numbers))
    sum= 0
    for i in numbers:
        sum = sum + i
    #  print("Average is : ",sum/len(numbers))
    return sum /len(numbers)
c = average(5,6,7,1)
print(c)

In [ ]:
print(15+6)
print(15-6)
print(15*6)
print(15/6)
print(15%6)
print(5**6)
print(15//6)
a=30
b=45
print("Sum of ",a,"+",b,"=",a+b)
print("Sum of ",a,"-",b,"=",a-b)
print("Sum of ",a,"*",b,"=",a*b)
print("Sum of ",a,"/",b,"=",a/b)
print("For duplicate in vs code'alt+shift+down key")

21
9
90
2.5
3
15625
2
Sum of  30 + 45 = 75
Sum of  30 - 45 = -15
Sum of  30 * 45 = 1350
Sum of  30 / 45 = 0.6666666666666666
For duplicate in vs code'alt+shift+down key